// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyB8F09hadirKqMsyb7v6_h795ACm9F98DY',
//     appId: '1:143923241958:web:e5e58e5100a96a58caec27',
//     messagingSenderId: '143923241958',
//     projectId: 'expense-calculator-firebase',
//     authDomain: 'expense-calculator-firebase.firebaseapp.com',
//     storageBucket: 'expense-calculator-firebase.firebasestorage.app',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyB8FgFXeD_je-SuqpOsKlBMYl2GMlBM1zg',
//     appId: '1:143923241958:android:55821b863e4b2ae1caec27',
//     messagingSenderId: '143923241958',
//     projectId: 'expense-calculator-firebase',
//     storageBucket: 'expense-calculator-firebase.firebasestorage.app',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAoX9ezLzxxaOmJoViCUYw2Nue-eYGmpMA',
//     appId: '1:143923241958:ios:e5276eb151987691caec27',
//     messagingSenderId: '143923241958',
//     projectId: 'expense-calculator-firebase',
//     storageBucket: 'expense-calculator-firebase.firebasestorage.app',
//     iosBundleId: 'com.example.expenseCalculatorDemo',
//   );
// }
